using Test
using ClimaOceanBiogeochemistry: CarbonAlkalinityNutrients, NutrientsPlanktonBacteriaDetritus

@test NutrientsPlanktonBacteriaDetritus() isa NutrientsPlanktonBacteriaDetritus
@test CarbonAlkalinityNutrients() isa CarbonAlkalinityNutrients
