name = "ClimaOceanBiogeochemistry"
uuid = "5cffcf50-4b89-4965-9f27-9db17d11d620"
authors = ["Climate Modeling Alliance and contributors"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[compat]
Oceananigans = "0.90.11"
RootSolvers = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
