name = "ClimaOceanBiogeochemistry"
uuid = "5cffcf50-4b89-4965-9f27-9db17d11d620"
authors = ["Climate Modeling Alliance and contributors"]
version = "0.1.0"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
